### PR TITLE
allow configuration of success message

### PR DESCRIPTION
**Pull request by rob-marr**
I'm running multiple concurrent rollup builds so needed a custom success message to know which one is finished.

### CODE REVIEW

**Comment by MikeKovarik** [comment]
Hey, thanks for the PR. I'm sorry, i didn't notice this was a PR, I only saw email title and thought it's another issue so i quickly put together `options.id` in the commit i pushed a minute ago. Would you try that and see if it works for you? thanks

**Comment by rob-marr** [comment]
No worries, I like your solution better than mine anyway, mine didn't tell you which build was failing 🤦🏻‍♂️ and it works fine:
Screen Shot 2019-09-07 at 13 34 35

**Comment by MikeKovarik** [comment]
Great, so I'll publish it on npm if there's nothing more to implement.

**Comment by rob-marr** [comment]
you could still add the changes that allow config of the message but It doesn't seem to useful now, just a nice to have

**Pull request closed without merging**
